# Generated by Django 4.1 on 2023-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_', '0002_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('red', 'red'), ('yellow', 'yellow'), ('orange', 'orange'), ('blue', 'blue'), ('teal', 'teal'), ('green', 'green'), ('purple', 'purple'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown')], default='white', max_length=7),
        ),
    ]
